[package]
name = "xx"
version = "0.1.0"
authors = ["prataprc <prataprc@gmail.com>"]
publish = false

[dependencies]
regex = "1"

[dependencies.nom]
version = "4.0.0"
features = ["regexp", "regexp_macros"]
